stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: harbor.anhld.biz/anhphuongshop/product-service:$CI_COMMIT_SHORT_SHA

#test commit

build:
  stage: build
  image: docker:20-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]
  script:
    # - docker info
    # - apk add docker-buildx-plugin
    - apk add docker-cli-buildx
    - echo "192.168.1.123 vaultdell.anhld.biz" >> /etc/hosts
    - echo "192.168.1.123 nexus.anhld.biz" >> /etc/hosts
    - ip a
    - chmod +x mvnw  # Ensure executable
    - DOCKER_BUILDKIT=1 docker build --build-arg NEXUS_USER="$NEXUS_USER" --build-arg NEXUS_PASS="$NEXUS_PASS" --add-host nexus.anhld.biz:192.168.1.123 -t $DOCKER_IMAGE .
    # - apk add --no-cache curl jq

    - echo "$HARBOR_PW" | docker login -u "$HARBOR_USER" --password-stdin "$HARBOR_URL"
    - docker push $DOCKER_IMAGE
  tags:
    - shared-runner-2

deploy:
 stage: deploy
 image: bitnamisecure/kubectl:latest
 variables:
   SECRET_NAME: "anhphuongshop-product-service-secrets"
   NAMESPACE: "anhphuongshop"
#    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
#    GIT_DEPTH: "0"
#    SONAR_TOKEN: "sqp_13b02f0e641f4198fdce787fedc51ca515f1ad1c"
 script:
    - echo "192.168.1.123 nexus.anhld.biz" >> /etc/hosts
    - apt-get update -qq && apt-get install -y curl jq
    - |
      cat <<EOF > /tmp/secret.yaml
      apiVersion: v1
      kind: Secret
      metadata:
        name: $SECRET_NAME
        namespace: $NAMESPACE
      type: Opaque
      data:
      $(curl --header "X-Vault-Token: ${VAULT_ID_TOKEN}" --request GET https://vaultdell.anhld.biz/v1/kv/data/anhphuongshop/product-service | jq -r '.data.data | to_entries[] | "  \(.key): \(.value | @base64) "')
      EOF

    - kubectl apply -f /tmp/secret.yaml
    - kubectl set image deployment/anhphuongshop-product-service-deployment anhphuongshop-product-service=$DOCKER_IMAGE -n anhphuongshop
 tags:
    - shared-runner-2
