spring.application.name=productservice
server.port=8084

#port chay grpc
grpc.server.port=9090  

spring.datasource.url=jdbc:postgresql://localhost:5432/anhphuongshop
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=productsvc


#OAuth2 Resource Server configuration
keycloak.base_url=http://localhost:8080
keycloak.realm=anhphuongshop
spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.base_url}/realms/${keycloak.realm}

logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.context.annotation=DEBUG
logging.level.org.springframework.core.type=TRACE

# Observability
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://192.168.1.51:4318/v1/traces

#aws credentials
aws.region=ap-southeast-2
aws.bucket_name=anhphuongshop-dev
# Kafka
spring.kafka.bootstrap-servers=192.168.1.161:9092
spring.kafka.consumer.group-id=inventory-payment-group
