spring.application.name=productservice
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/anhphuongshop
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=productsvc


#OAuth2 Resource Server configuration
keycloak.base_url=http://localhost:8080
keycloak.realm=anhphuongshop
spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.base_url}/realms/${keycloak.realm}

logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.springframework.web=DEBUG